{% set name = "cabal" %}
{% set version = "3.0.1.0" %}
{% set sha256 = "7707fdabfe1b07cf30cef19aad41066ef2283fc5512a5c5066ddb7e8e60205a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/haskell/cabal/archive/Cabal-v{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - ghc-bootstrap
    - zlib
    - gmp
test:
  commands:
    - cabal --help

about:
  home: https://haskell.org/cabal/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: cabal-install is the command line interface to Cabal and hackage.

  doc_url: https://www.haskell.org/cabal/index.html
  dev_url: https://github.com/haskell/cabal/tree/master/cabal-install

extra:
  recipe-maintainers:
    - eggzilla
