context:
  version: "3.10.3.0"

package:
  name: cabal
  version: ${{ version }}

source:
  - url: https://github.com/haskell/cabal/archive/refs/tags/cabal-install-v${{ version }}.tar.gz
    sha256: 075fba81fca61f6957dae3a542a3213415682dd9767f6ccdf3f9059f2cd0f156

  - if: linux
    then:
      url: https://downloads.haskell.org/~cabal/cabal-install-${{ version }}/cabal-install-${{ version }}-x86_64-linux-centos7.tar.xz
      sha256: cd3907c769f02f687f388a3d8191da2d78e26e1b5abf8bab78f2ed15589382bf
      target_directory: cabal-bootstrap
  - if: osx
    then:
      url: https://downloads.haskell.org/~cabal/cabal-install-${{ version }}/cabal-install-${{ version }}-x86_64-darwin.tar.xz
      sha256: 55f7d9e99b8e2d4e0e193b2f0275501e6d9c1ebd29cadbea6a0da48a8587e3e0
      target_directory: cabal-bootstrap
  - if: not unix
    then:
      url: https://downloads.haskell.org/~cabal/cabal-install-${{ version }}/cabal-install-${{ version }}-x86_64-windows.zip
      sha256: b651ca732998eba5c0e54f4329c147664a7fb3fe3e74eac890c31647ce1e179a
      target_directory: cabal-bootstrap
    

build:
  number: 1

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - perl
    - pkg-config
    - ghc-bootstrap ==9.6.7
    - if: not unix
      then:
        - binutils
        - m2-bash
        - m2-coreutils
        - m2-diffutils
        - m2-file
        - m2-gawk
        - m2-grep
        - m2-unzip
        - m2-which
  host:
    - if: linux
      then:
        - gmp
        - zlib
    - if: osx
      then:
        - libiconv

tests:
  - script: |
      cabal --version

about:
  homepage: https://github.com/haskell/cabal
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'cabal-install is the command line interface to Cabal and hackage.'
  documentation: https://www.haskell.org/cabal/index.html
  repository: https://github.com/haskell/cabal

extra:
  recipe-maintainers:
    - MementoRC
    - eggzilla
