context:
  version: "3.8.1.0"

package:
  name: cabal
  version: ${{ version }}

source:
  - url: https://github.com/haskell/cabal/archive/refs/tags/cabal-install-v${{ version }}.tar.gz
    sha256: e547d8ef7d86c8f1633b23d28bed3a8457bf08db3a382e4b4faa1cc7e8de0393

  - if: linux
    then:
      url: https://downloads.haskell.org/~cabal/cabal-install-${{ version }}/cabal-install-${{ version }}-x86_64-linux-deb10.tar.xz
      sha256: c71a1a46fd42d235bb86be968660815c24950e5da2d1ff4640da025ab520424b
      target_directory: cabal-bootstrap
  - if: osx
    then:
      url: https://downloads.haskell.org/~cabal/cabal-install-${{ version }}/cabal-install-${{ version }}-x86_64-darwin.tar.xz
      sha256: f5ff69127b0e596b0d7895a2b0b383543aa92ae46d9b1b28f2868d2a97ed0de9
      target_directory: cabal-bootstrap
  - if: not unix
    then:
      url: https://downloads.haskell.org/~cabal/cabal-install-${{ version }}/cabal-install-${{ version }}-x86_64-windows.zip
      sha256: b6dd6afe0e5a883f84dc52d836af0e90d9cd2b2978dd87200332085ecb4a0315
      target_directory: cabal-bootstrap
    

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - perl
    - pkg-config
    - ghc-bootstrap ==9.6.7
    - if: not unix
      then:
        - binutils
        - m2-bash
        - m2-coreutils
        - m2-diffutils
        - m2-file
        - m2-gawk
        - m2-grep
        - m2-unzip
        - m2-which
  host:
    - if: linux
      then:
        - gmp
        - zlib
    - if: osx
      then:
        - libiconv

tests:
  - script: |
      cabal --version

about:
  homepage: https://github.com/haskell/cabal
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'cabal-install is the command line interface to Cabal and hackage.'
  documentation: https://www.haskell.org/cabal/index.html
  repository: https://github.com/haskell/cabal

extra:
  recipe-maintainers:
    - MementoRC
    - eggzilla
