travis:
  secure:
    BINSTAR_TOKEN: NubT+BvFEBwaEOCPjvJ49tV0R1XoPBBj0qK+AKnCbtztGBjqjAR1D2PHP7d6y+7rehgGXEOjWXsAocGLQja3bV47oOMjylpfWlAP7s1lzXSc4OKTJCUGA0GeV1VrwEQHOMkso+kp0ovT8tEpojTbRyw4zNOaMwxGdq/VBrxjDZkkDvWjCOVo/EIgx8SNQP/GCajpZnjEHcDQxzFN7MhtSzYVJ6Ly0AeCAlHzDatHmggHMovob4VDMmhhKgI6K61ZBbYMzvlxIHxsfEfCVAF6r+on7vpFNgWjTT9nfgmO++8hfSFekOHyPuJ5klnl9CSDVYxJI360MNgYImhqFnNERS9xbGW5Owe4J2H8iMmspR30QyTW8EwQnibBsQZRMPV/eF6HTt/MbAypaYVR714IaP0fR/xZcrQK3lkn0gt5vVDduBhkoJ7uLoQod6Fw22pFUjVHk3E0Uss89eMwRkW6ym5NaOXo/IUkgm29OniA3V0myAjCkVaZoe1D70lGBwbCUp8RFdDtz7YnYQvzyjunCPINeUcrc9gY7Q3rpvLTYUdlbiNsf+xy1J8opqcBhzHMZrInXj8AT1LHmiXRtUzwMDYUgGvhySYHA/61bTWT9bOXi/9YhEzj4eP/eqWHgvJYSaJ7nu4jP8cKi0HjLySkARCBy8TBadkXLEGd8Gv3m/Y=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
